module.exports = {

	//events
	'LOAD_FEED_COMPLETE' : 'LOAD_FEED_COMPLETE',  
	'FB_LINK_ERROR' : 'FB_LINK_ERROR',
	'FB_PIC_ERROR' : 'FB_PIC_ERROR',
	'SCRAPE_COMPLETE' : 'SCRAPE_COMPLETE',
	'SCRAPE_ERROR' : 'SCRAPE_ERROR',
	'DB_ADD_ERROR' : 'DB_ADD_ERROR',
	'DB_ADD_COMPLETE' : 'DB_ADD_COMPLETE',
	'SEARCH_FRIENDS_COMPLETE': 'SEARCH_FRIENDS_COMPLETE',
	'SEARCH_FRIENDS_ERROR': 'SEARCH_FRIENDS_ERROR',
	'DB_ERROR': 'DB_ERROR',
	'ADD_FRIEND_COMPLETE': 'ADD_FRIEND_COMPLETE',
	'GET_FRIENDS_COMPLETE': 'GET_FRIENDS_COMPLETE',
	'REMOVE_FRIEND_COMPLETE': 'REMOVE_FRIEND_COMPLETE',
	"ALL_ITEMS_ADDED": "ALL_ITEMS_ADDED",
	"ADDED_ARTICLE_BY_ID_COMPLETE": "ADDED_ARTICLE_BY_ID_COMPLETE",
	"SEARCH_HASH_ERROR": "SEARCH_HASH_ERROR",
	"SEARCH_HASH_COMPLETE": "SEARCH_HASH_COMPLETE",
	"SHARE_COMPLETE": "SHARE_COMPLETE",

	//posts
	"FB_POST_COMPLETE": "FB_POST_COMPLETE",
	"TWITTER_POST_COMPLETE": "TWITTER_POST_COMPLETE",
	"GOOGLE_POST_COMPLETE": "GOOGLE_POST_COMPLETE",
	"TUMBLR_POST_COMPLETE": "TUMBLR_POST_COMPLETE",
	"MAIL_POST_COMPLETE": "MAIL_POST_COMPLETE",

	//other
	"PLACEHOLDER_IMAGE": "//placehold.it/200x150",
	"GOOGLE_SCOPES": ['https://www.googleapis.com/auth/plus.login',
				'https://www.googleapis.com/auth/userinfo.profile', 
                'https://www.googleapis.com/auth/userinfo.email'],
    "FACEBOOK_SCOPES": ['public_profile', 'read_stream', 'publish_actions', 'user_friends', 'email'],
    "PAGE_LIMIT": 40,
    "TIME_DIFF": 15

};